
path_to_FASTA  <- paste(UserOutput,"/Desktop/CDMAP_Output/GC_directory/FASTA", sep = "")
path_to_chrome  <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/Chromosome/T", sep = "")
path_to_Lcore  <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/Lcore/T", sep = "")
path_to_Rcore <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/Rcore/T", sep = "")
path_to_Lcore_Rep <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/Lcore_Replichore/T", sep = "")
path_to_Rcore_Rep <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/Rcore_Replichore/T", sep = "")
path_to_RevComp_chrome  <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/RevComp_Chromosome/T", sep = "")
path_to_RevComp_Lcore  <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/RevComp_Lcore/T", sep = "")
path_to_RevComp_Rcore <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/RevComp_Rcore/T", sep = "")
path_to_RevComp_Lcore_Rep  <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/RevComp_Lcore_Replichore/T", sep = "")
path_to_RevComp_Rcore_Rep <- paste(UserOutput,"/Desktop/CDMAP_Output/Correlation_Repository/Upstream/RevComp_Rcore_Replichore/T", sep = "")
